server:
  port : 8080
  servlet:
    context-path: /
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msGraph
    username: graph
    password: csi3335rocks
  sql:
    init:
      platform: mariadb